### ISSUE TITLE
Outbound emails will be flagged as SPF/DKIM invalid and marked as phishing/spam.

### ISSUE THREAD

**Issue by jturolla** [mthbernardes/WhoAmIMailBot#1]
- could be mitigated by running a dedicated domain name.

[1] https://en.wikipedia.org/wiki/DomainKeys_Identified_Mail

**Comment by mthbernardes** [comment]
Yep, it's a know issue, but you can't set it on no-ip domains. So if you don't want all your e-mails going to spam, just buy a domain using BTC. :laughing:
